-- Create a table for public user profiles
create table profiles (
  id uuid references auth.users not null,
  email text,
  full_name text,
  avatar_url text,
  is_pro boolean default false,
  stripe_customer_id text,
  stripe_subscription_id text,
  stripe_price_id text,
  stripe_current_period_end timestamp with time zone,
  daily_usage_count integer default 0,
  last_usage_date date default current_date,
  updated_at timestamp with time zone,
  primary key (id),
  constraint username_length check (char_length(full_name) >= 3)
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for storing copy drafts
create table drafts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  type text not null,
  audience text,
  goal text,
  content jsonb not null, -- Stores the main and alt versions
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table drafts enable row level security;

create policy "Users can view own drafts."
  on drafts for select
  using ( auth.uid() = user_id );

create policy "Users can insert own drafts."
  on drafts for insert
  with check ( auth.uid() = user_id );

create policy "Users can update own drafts."
  on drafts for update
  using ( auth.uid() = user_id );
