-- Create a table for subscriptions
create table subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  stripe_subscription_id text not null,
  status text not null,
  plan_id text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table subscriptions enable row level security;

-- Allow users to read their own subscription data
create policy "Users can view own subscription" on subscriptions
  for select using (auth.uid() = user_id);

-- Only service role can insert/update (via webhook)
create policy "Service role can insert subscription" on subscriptions
  for insert with check (true);

create policy "Service role can update subscription" on subscriptions
  for update using (true);
